### ISSUE TITLE
How to handle returned data from the library

### ISSUE THREAD

**Issue by Petrit-Halabaku** [activescott/cookieconsent#86]
@activescott 

# Upon start, the library gives us these data, of course, if you choose the `type: "categories"`.
![Untitled](https://user-images.githubusercontent.com/19550291/139744294-dbec1fb0-668d-4e82-97fa-32caaf928d11.png)

> ### How can we use these data and those chosen by the user and return us an object/array so that we can manipulate those data? This is the returned data after choosing one of the boxes and submitting the form.

![Untitled](https://user-images.githubusercontent.com/19550291/139744819-9495e12f-a2b4-4b8f-b911-9de93af579ee.png)

**Comment by activescott** [comment]
@Petrit-Halabaku I created an example and put it in the `docs/events-example` branch. Direct link to the example at https://github.com/activescott/cookieconsent/tree/docs/events-example/examples-new/events

Does this answer your question?

**Comment by activescott** [comment]
From that example, this is the bit that matters: https://github.com/activescott/cookieconsent/blob/c9cc7d8aa9bb064fb8ec03c96b528af3694e703b/examples-new/events/index.html#L20

**Comment by activescott** [comment]
As far as I can tell this is resolved in #87. Please let me know if I missed something.

**Comment by activescott** [comment]
published in release v5.1.0:
- https://github.com/activescott/cookieconsent/releases/tag/v5.1.0
- https://www.npmjs.com/package/@activescott/cookieconsent

updated example at https://github.com/activescott/cookieconsent/blob/dev/examples-new/events/index.html
