### ISSUE TITLE
Cookie classification/execution problem

### ISSUE THREAD

**Issue by Petrit-Halabaku** [activescott/cookieconsent#89]
**How are  🍪 🍪  categorized and run on toggle of the consent button**
@activescott  I was creating a custom cookie consent popup and came to a point where I had to send something back to the backend, but I am struggling to grasp how are cookies grouped and run if and when the user selects one of the categories?

**Comment by activescott** [comment]
sorry for the delay. I'm not sure I totally follow your question. Maybe you could submit a sample that shows the problem and I could try to advise then. Remember, I forked this library from https://github.com/osano/cookieconsent and I am not necessarily an expert but you might be able to find out some details by looking through the code or some of osano's examples (personally I just look through the code)
